### PR TITLE
Bump plugin parent POM from 4.31 to 4.33

### PR DESCRIPTION
**Pull request by basil**
Supersedes #74.

### CODE REVIEW

**Comment by basil** [comment]
@car-roll Is there a reason why this PR has remained unacknowledged for 3 months?

**Review by car-roll — APPROVED** [review]

**Comment by car-roll** [comment]
@basil not a _good_ reason, unfortunately: I don't normally pay attention to this repository

**Comment by basil** [comment]
Thanks @car-roll. A release of this would facilitate Java 17 PCT testing.

**Comment by basil** [comment]
Thank you!

**Pull request merged**
