### PR TITLE
Mark pipeline waitForBuild step with the downstream build result

### PR DESCRIPTION
**Pull request by stuartrowe**
Add a WarningAction to the `waitForBuild` step FlowNode when the downstream build isn't successful.

Also, log the build result when the downstream run completes.

This is the `waitForBuild` step equivalent of https://github.com/jenkinsci/pipeline-build-step-plugin/pull/107.

Implements https://issues.jenkins.io/browse/JENKINS-70983

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by stuartrowe** [comment]
Exception during `Publish Coverage Report` step:
```
java.util.concurrent.ExecutionException: Invalid object ID 66 iota=70
```

**Comment by stuartrowe** [comment]
Re-opening to trigger a new build.

**Comment by stuartrowe** [comment]
@car-roll @olamy please review when you have a chance.

**Comment by stuartrowe** [comment]
@car-roll @olamy poking for a review.

**Review by olamy — APPROVED** [review]
lgtm

**Comment by stuartrowe** [comment]
@olamy could you please merge this so it can be released? Thanks!

**Pull request merged**
