### PR TITLE
JENKINS-46311 Show las 1000 lines of logs from Downstream jobs.

### PR DESCRIPTION
**Pull request by roidelapluie**
I am looking for help & guidance for this pull request.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Hi @jglick yes that is what I want. I just have no idea how I can do it yet.

**Comment by roidelapluie** [comment]
@jglick Hi...

Improved version...

- still no tests
- race condition (last second of the logs is not printed)

**Comment by roidelapluie** [comment]
but there is streaming now

**Comment by Dmitry1987** [comment]
Hi guys, was this abandoned?  Is there a way to pull logs from downstream jobs?

**Comment by jglick** [comment]
Abandoned. No opt-in/out, no truncation, no support for controller restarts, etc. At this point I doubt we would even want something like this; better to enhance pipeline visualizations to better navigate to downstream builds.

**Pull request closed without merging**
