### PR TITLE
[JENKINS-65324] added a missing online help

### PR DESCRIPTION
**Pull request by ciradu2204**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
   I added a missing online help for the wait argument 
- [x] Link to relevant issues in GitHub or Jira
  https://issues.jenkins.io/browse/JENKINS-65324
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by ciradu2204** [comment]
Hi @MarkEWaite and @Stackscribe, 

Here is my pull request for the missing pipeline help task. I am looking forward to your feedback. Thanks

**Comment by MarkEWaite** [comment]
@basil do you have permission to merge this pull request and #49 ?  The [SheCodeAfrica Contributhon](https://www.jenkins.io/blog/2021/04/07/contributhon-participants/) is working during April to improve the Pipeline step descriptions, Pipeline argument descriptions, and Pipeline examples.  We'd love to have fast review of their work

**Comment by basil** [comment]
> @basil do you have permission to merge this pull request and #49 ?

I do not; as far as I can tell, @dwnusbaum is the primary maintainer of the Pipeline plugins who merges PRs. Let me know if there's any way I can help.

**Review by kwhetstone — COMMENTED** [review]
I think the pattern of help documentation is to explain what the setting does, and then to state the default.  Otherwise, this looks fine to me.

**Review by oleg-nenashev — COMMENTED** [review]
+1 to what @kwhetstone said. Also please add line break at the end of the file

**Comment by ciradu2204** [comment]
@kwhetstone and @oleg-nenashev, thank you for the feedback. I have made changes.

**Review by aHenryJard — APPROVED** [review]
Looks good to me

**Review by oleg-nenashev — APPROVED** [review]

**Review by alecharp — APPROVED** [review]

**Review by MRamonLeon — APPROVED** [review]

**Comment by ciradu2204** [comment]
Hi  @MarkEWaite @kwhetstone, I have worked on your reviews. If there are no other improvements you want me to make, it would be amazing if you accept this PR and merge it. Thank you!

**Review by bitwiseman — APPROVED** [review]

**Pull request merged**
