### PR TITLE
Refresh plugin

### PR DESCRIPTION
**Pull request by basil**
This is required for https://github.com/jenkinsci/stapler/pull/452 so that tests continue passing in this plugin and in BOM.

### CODE REVIEW

**Comment by basil** [comment]
Used my admin powers to replay the build with the `Jenkinsfile` changes here: https://ci.jenkins.io/job/Plugins/job/pipeline-build-step-plugin/job/PR-113/2/

**Comment by basil** [comment]
Please release this for BOM purposes

**Comment by basil** [comment]
CC @jenkinsci/pipeline-build-step-plugin-developers

**Review by jglick — APPROVED** [review]

**Comment by jglick** [comment]
https://github.com/jenkinsci/pipeline-build-step-plugin/releases/tag/490.v7df200b_9b_ef3

**Comment by basil** [comment]
Thank you!

**Pull request merged**
