### PR TITLE
Code clean-up and  improvements

### PR DESCRIPTION
**Pull request by offa**
Some code enhancements. This includes replacing JSR 305 annotations.

-------------------------

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by basil — APPROVED** [review]

**Review by basil — APPROVED** [review]
@car-roll FYI the JSR 305 changes in this PR are needed for the next plugin parent POM update.

**Review by car-roll — APPROVED** [review]

**Comment by offa** [comment]
@car-roll Conflicts resolved.

**Review by car-roll — APPROVED** [review]

**Comment by car-roll** [comment]
@offa I need to get permission to this repo before I can merge

**Comment by dwnusbaum** [comment]
@car-roll you should have permission now

**Pull request merged**
