### PR TITLE
Wrong package in tests

### PR DESCRIPTION
**Pull request by amuniz**
BTW how could this compile before?

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
:bee: FYI http://stackoverflow.com/questions/8395916/package-name-is-different-than-the-folder-structure-but-still-java-code-compiles

**Comment by andresrc** [comment]
:bee:

**Comment by amuniz** [comment]
@jglick can you merge please? I don't have push permission (although I received a notification saying so when `(workflow|pipeline)-*` repos were created...)

**Comment by recena** [comment]
@amuniz Done.

**Comment by batmat** [comment]
@amuniz do you want me to kindly ask the bot to give your permission?

**Comment by amuniz** [comment]
@batmat if you can. I don't mind to have others merging, but sometimes there is no one around.

**Comment by batmat** [comment]
@amuniz done, you should have received an invitation.

**Pull request merged**
